version: "3.8"
services:
    app:
        build:
            context: ./app
        ports:
            - "8080:8080"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "4000:4000"